//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SafeFolder.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileRecipient
    {
        public int Id { get; set; }
        public int FileId { get; set; }
        public int AddressBookId { get; set; }
    
        public virtual AddressBook AddressBook { get; set; }
        public virtual File File { get; set; }
    }
}
